<div class=box>
    <?php require_once 'form_items.phtml'?>
    <table class='Datos'>
        <tr>
            <th>Nombre</th>
            <th>Raza</th>
        </tr>
        <?php foreach ($items as $item) {
            echo "
                <tr>
                    <td>
                        {$item->nombre}
                    </td>
                    <td>
                        {$item->raza}
                    </td>
                    <td>
                        <a class='Botones' href=GetItem/{$item->id_gato}>Ver completo</a>
                    </td>
                </tr>";
        }?>
    </table>
</div>