<?php require_once __DIR__ . '/layout/header.phtml'?>

<div class=box>
    <?php 
    if ($request->user) {
        require_once 'form_items.phtml';
    }?>
    <table class='Datos'>
        <tr>
            <th>Nombre</th>
            <th>Raza</th>
        </tr>
        <?php foreach ($items as $item) {
            echo "
                <tr>
                    <td>
                        {$item->nombre}
                    </td>
                    <td>
                        {$item->raza}
                    </td>";
            if ($request->user) {
                echo "
                    <td>
                        <a class='Botones' href=GetItem/{$item->id_gato}>Ver completo</a>
                    </td>";
            }
            echo "
                </tr>";
        }?>
    </table>
</div>

<?php require_once __DIR__ . '/layout/footer.phtml'?>