<?php require_once __DIR__ . '/../layout/header.phtml';
/** @var object $item */

echo "
    <form action='UpdateItem/{$item->id_gato}' method='POST' class='form-addItem'>
<div class='col-form'>
    <div class='field'>
        <label>Nombre*</label>
        <input required name='name' type='text' value='{$item->nombre}'>
    </div>
    <div class='field'>
        <label>Edad* (Meses)</label>
        <input required name='age' type='number' class='age' value='{$item->edad_meses}'>
    </div>
</div>
<div class='col-form'>
    <div class='field'>
        <label>Raza*</label>
        <input required name='race' type='text' value='{$item->raza}'>
    </div>
    <div class='field'>
        <label>Color</label>
        <input name='color' type='text' value='{$item->color}'>
    </div>
</div>
<div class='col-form'>
    <div class='field'>
        <label>Peso* (KG)</label>
        <input required name='weight' type='text' value='{$item->peso_kg}'>
    </div>
</div>
<div class='col-form'>
    <div class='field'>
        <label>Observaciones</label>
        <textarea name='observations' rows='3'>{$item->observaciones}</textarea>
    </div>
</div>
<div class='col-form'>
    <div class='field'>
        <select name='peluquero'>
            <option value=''>N/A</option>";
                foreach($FK as $item) {
                    echo "
                        <option value='{$item->id_peluquero}'>{$item->nombre_apellido}</option>
                    ";
                }
        echo "</select>
    </div>
</div>
<div class='col-form'>
    <button type='submit' class='btn-item-submit'>Editar</button>
</div>";

require_once __DIR__ . '/../layout/footer.phtml';