<?php require_once __DIR__ . '/../layout/header.phtml'?>

<form action="Dologin" method="POST" class="my-4">
    <div class="row">
        <div class="col-9">
            <div class="form-group">
                <label>Usuario</label>
                <input required name="username" type="text" class="form-control">
            </div>
        </div>
        <div class="col-9">
            <div class="form-group">
                <label>Contraseña</label>
                <input required name="password" type="password" class="form-control">
            </div>
        </div>
        <div class="col-9 text-danger">
            <?php if (!empty($error)): ?>
                <?=$error?>
            <?php endif; ?>
    </div>
    <button type="submit" class="btn btn-primary mt-2">Logear</button>
</form>

<?php require_once __DIR__ . '/../layout/footer.phtml'?>