<?php require_once __DIR__ . '/header.phtml'?>

<div class="boxhome">
    <h1 class="hometext">Bienvenido !</h1>

    <h2 class="hometext">Para continuar, clickea en alguno de los botones en la barra de tareas</h2>

    <h3 class="hometext">Atentamente, Rodrigo Joaquin Membrilla</h3>

    <?php
        $hash='admin';
        $pass= password_hash($hash, PASSWORD_DEFAULT); 
        echo "{$pass}"; ?>
</div>

<?php require_once __DIR__ . '/footer.phtml'?>