<?php

class CategoryView {
    public function DisplayCategorias($categorias,$request) {
        require_once __DIR__ . '/../../template/Category/lista_categorias.phtml';
    }

    public function showError($error) {
        require_once __DIR__ . '/../../template/error.phtml';
    }

    public function DisplayCategoriaEdit($item,$request) {
        require_once __DIR__ . '/../../template/Category/form_edit_categoria.phtml';
    }

    public function DisplayBusqueda($categories,$request) {
        require_once __DIR__ . '/../../template/Category/form_busqueda.phtml';
    }

    
}