<?php

Class ItemView {
    public function DisplayItems($items,$FK,$request) {
        require_once __DIR__ . '/../../template/Item/lista_items.phtml';

    }

    public function DisplayItem($item,$FK,$request) {
        require_once __DIR__ . '/../../template/Item/item.phtml';
    }

    public function showError($error) {
        require_once __DIR__ . '/../../template/error.phtml';
    }

    public function DisplayItemEdit($item,$FK,$request) {
        require_once __DIR__ . '/../../template/Item/form_edit_item.phtml';
    }
}