<?php

Class ItemView {
    public function DisplayItems($items,$request) {

        require_once __DIR__ . '/../../template/lista_items.phtml';

    }

    public function DisplayItem($item,$request) {
        require_once __DIR__ . '/../../template/layout/header.phtml';
        echo "
        <ul>
            <li>Nombre: {$item->nombre}</li>
            <li>Edad: {$item->edad_meses} meses</li>
            <li>Raza: {$item->raza}</li>
            <li>Color: {$item->color}</li>
            <li>Peso: {$item->peso_kg} KG</li>
            <li>Observaciones: {$item->observaciones}</li>
        </ul>
        <a class='Botones' href='home'>Volver</a>
        <a class='Botones' href='editItem/{$item->id_gato}'>Editar</a>
        <a class='Botones' href='deleteItem/{$item->id_gato}'>Borrar</a>";
    }

    public function showError($error) {
        echo "<h1>$error</h1>";
    }

    public function DisplayItemEdit($item,$request) {
        require_once __DIR__ . '/../../template/layout/header.phtml';
        echo "
        <form action='UpdateItem/{$item->id_gato}' method='POST' class='form-addItem'>
    <div class='col-form'>
        <div class='field'>
            <label>Nombre*</label>
            <input required name='name' type='text' value='{$item->nombre}'>
        </div>
        <div class='field'>
            <label>Edad* (Meses)</label>
            <input required name='age' type='number' class='age' value='{$item->edad_meses}'>
        </div>
    </div>
    <div class='col-form'>
        <div class='field'>
            <label>Raza*</label>
            <input required name='race' type='text' value='{$item->raza}'>
        </div>
        <div class='field'>
            <label>Color</label>
            <input name='color' type='text' value='{$item->color}'>
        </div>
    </div>
    <div class='col-form'>
        <div class='field'>
            <label>Peso* (KG)</label>
            <input required name='weight' type='text' value='{$item->peso_kg}'>
        </div>
    </div>
    <div class='col-form'>
        <div class='field'>
            <label>Observaciones</label>
            <textarea name='observations' rows='3'>{$item->observaciones}</textarea>
        </div>
    </div>
    <div class='col-form'>
        <button type='submit' class='btn-item-submit'>Editar</button>
    </div>";
    }
}